config/routes.rb
Rails.application.routes.draw do
  resources :letters
  root "letters#index"
end

app/models/letter.rb
class Letter < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
  validates :addressed_to, presence: true
  validates :body, presence: true
  paginates_per 6
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  http_basic_authenticate_with name: "acmecorp", password: "thisisakey"
	def index
    @letters = Letter.all.order('created_at DESC').page params[:page]
	end
	def new
		@letter = Letter.new
	end
	def show
    @letter = Letter.find(params[:id])
  end
	def create
    @letter = Letter.new(letter_params)
    if @letter.save
    redirect_to @letter
  	else
    render 'new'
  end
	end

  private
 
  def letter_params
    params.require(:letter).permit(:title, :body, :addressed_to)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/layouts/_footer.html.erb
<i>an open source project by <a href="http://github.com/nshntarora">@nshntarora</a></i>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Openletters</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Materialize Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body class="#26a69a teal lighten-1">
  <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <%= link_to(content_tag(:i, "add", class: "large material-icons"), new_letter_path, class: "btn-floating btn-large teal darken-4")%>
  </div>
  <div class="site-header">
  <%= link_to(content_tag(:h1, "Open Letters", class: "header center white-text"), root_path )%>
<div class="row center">
        <h5 class="header col s12 light white-text">with great power comes great responsibility.</h5>
      </div>
      </div>
	<div class="container">
<%= yield %>
</div>
<div class="a-little-link"><center>an open source project by <a href="http://github.com/nshntarora">@nshntarora</a></center></div>
</body>
</html>

app/views/letters/_form.html.erb
<div class="form-inputs"><%= simple_form_for @letter do |f| %>
  <% if @letter.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@letter.errors.count, "error") %> prevented this letter from saving:</h2>
      <ul>
        <% @letter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title, placeholder: "Letter Title" %>
  <%= f.input :addressed_to, label: "Addressed To", placeholder: "Addressed to" %>
  <%= f.input :body, placeholder: "Letter Body"%>
<center>
  <%= f.submit "Submit", class: "btn-large" %>
</center>
<% end %>
</div>

app/views/letters/index.html.erb
<% @letters.each do |letter| %>
  <%= link_to letter, :class => 'letter-block' do %>
    <h5 class="index-title grey-text text-darken-1"><%= letter.title %></h5>
    <p class="date grey-text text-darken-2">Addressed to <%= letter.addressed_to %> | <i>Published <%= time_ago_in_words(letter.created_at) %> ago</i></p>
    <hr>
<% end %>
<% end %>
<center>
<%= paginate @letters %>
</center>

app/views/letters/new.html.erb
<center><h4 class="new-letter">Write a letter</h4></center>
<%=render 'form'%>

app/views/letters/show.html.erb
<div class="letter-wrapper">
<h1 class="title">
  <%= @letter.title %>
</h1>
<p class="date">
  <b>Addressed to <%= @letter.addressed_to %></b> | <i>Submitted <%= time_ago_in_words(@letter.created_at) %> ago</i>
</p>
 <p class="body">
  <%= @letter.body %>
</p>
</div>